// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4");

                    b.Property<string>("PostDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Breed = "German Shepherd",
                            Name = "Dara",
                            PostDate = "16 August 2022",
                            Species = "dog!!"
                        },
                        new
                        {
                            AnimalId = 2,
                            Breed = "Klee Kai",
                            Name = "Blaze",
                            PostDate = "16 August 2022",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Breed = "Klee Kai",
                            Name = "Buddy",
                            PostDate = "16 August 2022",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Breed = "Siamese",
                            Name = "Dodger",
                            PostDate = "16 August 2022",
                            Species = "cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
